title: Encurtador de LInks Fonte de Deus
description: Este é um encurtador de links estático
logo: /assets/img/logo.png
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal

permalink: /:slug/

plugins:
  - jekyll-redirect-from

#repository: hlaueriksson/jekyll-url-shortener
